import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function renderChecklist(items) {
  return items.map((item) => `- [ ] ${item.item}`).join('\n');
}

function renderScorecardRows(scorecard) {
  return [
    '| Signal | Status | Weight | Evidence | Next action |',
    '| --- | --- | --- | --- | --- |',
    ...scorecard.map((item) => `| ${item.label} | ${item.passed ? 'Supported' : 'Gap'} | ${item.weight} | ${item.evidence[0] || 'No direct evidence found in profile.'} | ${item.nextAction || 'Keep reinforcing this signal.'} |`),
  ].join('\n');
}

export function renderFlagshipMarkdown(dossier) {
  const metricRows = [
    '| Metric | Score |',
    '| --- | --- |',
    `| Proof density | ${dossier.metrics.proofDensity}/100 |`,
    `| Claim support ratio | ${dossier.metrics.claimSupportRatio}/100 |`,
    `| Portfolio clarity | ${dossier.metrics.portfolioClarity}/100 |`,
    `| Recruiter scan readiness | ${dossier.metrics.recruiterScanReadiness}/100 |`,
  ];

  return [
    `# ${dossier.summary.title}`,
    '',
    `Generated by Occupation-Ops. Profile source: ${dossier.source}`,
    '',
    '## Product Positioning',
    '',
    `${dossier.rubricName} is a proof-before-applying workflow for ${dossier.summary.audience}.`,
    '',
    `Current score: ${dossier.summary.scoreTen}/10 (${dossier.summary.scorePercent}%).`,
    '',
    '## Proof Inventory',
    '',
    ...dossier.profile.currentProof.map((item) => `- ${item}`),
    '',
    '## Role Gap Scorecard',
    '',
    renderScorecardRows(dossier.scorecard),
    '',
    '## Public Proof Metrics',
    '',
    ...metricRows,
    '',
    '## Prioritized Proof Backlog',
    '',
    ...dossier.backlog.map((item) => `${item.priority}. ${item.title} - ${item.nextAction}`),
    '',
    '## GitHub Profile Rewrite',
    '',
    dossier.githubPlan.headlineRewrite,
    '',
    '## README Improvement Checklist',
    '',
    renderChecklist(dossier.githubPlan.readmeChecklist),
    '',
    '## Portfolio Project Briefs',
    '',
    ...dossier.projects.flatMap((project, index) => [
      `### Project ${index + 1}: ${project.title}`,
      '',
      `Problem: ${project.problem}`,
      '',
      `Solution: ${project.solution}`,
      '',
      `Recruiter takeaway: ${project.recruiterTakeaway}`,
      '',
      'Interview talking points:',
      ...project.interviewTalkingPoints.map((point) => `- ${point}`),
      '',
    ]),
    '## Interview Story Map',
    '',
    ...dossier.interviewMap.map((item) => `- ${item.topic}: ${item.proofPrompt}`),
    '',
    '## Weekly Shipping Plan',
    '',
    `Theme: ${dossier.weeklyPlan.weeklyTheme}`,
    '',
    '| Day | Task | Proof artifact |',
    '| --- | --- | --- |',
    ...dossier.weeklyPlan.dailyPlan.map((item) => `| ${item.day} | ${item.task} | ${item.proofArtifact} |`),
    '',
    '## Artifact Validators',
    '',
    ...dossier.validators.map((validator) => `- ${validator.label}: ${validator.status.toUpperCase()} - ${validator.detail}`),
    '',
    '## Truthfulness Guardrails',
    '',
    ...dossier.truthfulnessGuardrails.map((item) => `- ${item}`),
    '',
    '## Occupation-Ops vs Job Search Pipeline Tools',
    '',
    ...dossier.comparison.map((item) => `- ${item}`),
    '',
  ].join('\n');
}

export function renderHtmlViewer(dossier) {
  const data = JSON.stringify(dossier).replace(/</g, '\\u003c');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${dossier.summary.title}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f6f1e8;
      --panel: rgba(255,255,255,0.82);
      --ink: #172126;
      --muted: #5f6a70;
      --line: rgba(23,33,38,0.12);
      --accent: #0f766e;
      --accent-soft: rgba(15,118,110,0.12);
      --warn: #b45309;
      --fail: #b91c1c;
      --shadow: 0 24px 60px rgba(23,33,38,0.08);
      font-family: "Segoe UI", system-ui, sans-serif;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background:
        radial-gradient(circle at top left, rgba(15,118,110,0.16), transparent 28%),
        radial-gradient(circle at top right, rgba(180,83,9,0.14), transparent 30%),
        var(--bg);
      color: var(--ink);
    }
    main { width: min(1160px, calc(100% - 32px)); margin: 32px auto 56px; }
    .hero, .panel {
      background: var(--panel);
      backdrop-filter: blur(14px);
      border: 1px solid var(--line);
      border-radius: 24px;
      box-shadow: var(--shadow);
    }
    .hero { padding: 32px; }
    .eyebrow { text-transform: uppercase; letter-spacing: 0.12em; color: var(--muted); font-size: 12px; }
    h1 { margin: 12px 0 8px; font-size: clamp(2rem, 5vw, 4rem); line-height: 0.95; }
    .lede { color: var(--muted); max-width: 60ch; font-size: 1.05rem; }
    .metrics, .grid, .cards { display: grid; gap: 16px; }
    .metrics { grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); margin-top: 24px; }
    .metric, .card { background: #fff; border-radius: 18px; border: 1px solid var(--line); padding: 18px; }
    .metric strong { display: block; font-size: 2rem; margin-top: 10px; }
    .grid { grid-template-columns: 1.1fr 0.9fr; margin-top: 20px; }
    .panel { padding: 24px; }
    h2 { margin: 0 0 16px; font-size: 1.2rem; }
    ul { margin: 0; padding-left: 18px; }
    li + li { margin-top: 8px; }
    .cards { grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); }
    .status { display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; }
    .pass { background: rgba(15,118,110,0.12); color: var(--accent); }
    .warn { background: rgba(180,83,9,0.12); color: var(--warn); }
    .fail { background: rgba(185,28,28,0.12); color: var(--fail); }
    table { width: 100%; border-collapse: collapse; font-size: 0.95rem; }
    th, td { text-align: left; padding: 10px 0; border-bottom: 1px solid var(--line); vertical-align: top; }
    .muted { color: var(--muted); }
    @media (max-width: 820px) { .grid { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <main id="app"></main>
  <script type="application/json" id="dossier">${data}</script>
  <script>
    const dossier = JSON.parse(document.getElementById('dossier').textContent);
    const app = document.getElementById('app');
    const metric = (label, value) => \`<div class="metric"><div class="muted">\${label}</div><strong>\${value}</strong></div>\`;
    const statusClass = (value) => value === 'pass' ? 'pass' : value === 'warn' ? 'warn' : 'fail';
    app.innerHTML = \`
      <section class="hero">
        <div class="eyebrow">Occupation-Ops flagship proof dossier</div>
        <h1>\${dossier.summary.title}</h1>
        <p class="lede">\${dossier.summary.positioning}</p>
        <div class="metrics">
          \${metric('Role proof score', dossier.summary.scoreTen + '/10')}
          \${metric('Proof density', dossier.metrics.proofDensity + '/100')}
          \${metric('Claim support ratio', dossier.metrics.claimSupportRatio + '/100')}
          \${metric('Recruiter scan readiness', dossier.metrics.recruiterScanReadiness + '/100')}
        </div>
      </section>
      <div class="grid">
        <section class="panel">
          <h2>Prioritized proof backlog</h2>
          <ul>\${dossier.backlog.map(item => \`<li><strong>\${item.title}</strong><br><span class="muted">\${item.nextAction}</span></li>\`).join('')}</ul>
        </section>
        <section class="panel">
          <h2>GitHub headline rewrite</h2>
          <p>\${dossier.githubPlan.headlineRewrite}</p>
          <h2 style="margin-top:24px;">README checklist</h2>
          <ul>\${dossier.githubPlan.readmeChecklist.map(item => \`<li>\${item.item}</li>\`).join('')}</ul>
        </section>
      </div>
      <section class="panel" style="margin-top:20px;">
        <h2>Role gap scorecard</h2>
        <table>
          <thead><tr><th>Signal</th><th>Status</th><th>Evidence</th><th>Next action</th></tr></thead>
          <tbody>
            \${dossier.scorecard.map(item => \`<tr><td>\${item.label}</td><td><span class="status \${item.passed ? 'pass' : 'warn'}">\${item.passed ? 'Supported' : 'Gap'}</span></td><td>\${item.evidence[0] || 'No direct evidence found.'}</td><td>\${item.nextAction || 'Keep reinforcing this signal.'}</td></tr>\`).join('')}
          </tbody>
        </table>
      </section>
      <section class="panel" style="margin-top:20px;">
        <h2>Artifact validators</h2>
        <div class="cards">
          \${dossier.validators.map(item => \`<article class="card"><span class="status \${statusClass(item.status)}">\${item.status.toUpperCase()}</span><h3>\${item.label}</h3><p class="muted">\${item.detail}</p></article>\`).join('')}
        </div>
      </section>
      <section class="panel" style="margin-top:20px;">
        <h2>Weekly shipping plan</h2>
        <table>
          <thead><tr><th>Day</th><th>Task</th><th>Proof artifact</th></tr></thead>
          <tbody>
            \${dossier.weeklyPlan.dailyPlan.map(item => \`<tr><td>\${item.day}</td><td>\${item.task}</td><td>\${item.proofArtifact}</td></tr>\`).join('')}
          </tbody>
        </table>
      </section>
    \`;
  </script>
</body>
</html>`;
}

export function writeOutputBundle(baseName, dossier, markdown) {
  const outputDir = join(process.cwd(), 'output');
  mkdirSync(outputDir, { recursive: true });

  const jsonPath = join(outputDir, `${baseName}.json`);
  const markdownPath = join(outputDir, `${baseName}.md`);
  const htmlPath = join(outputDir, `${baseName}.html`);

  writeFileSync(jsonPath, `${JSON.stringify(dossier, null, 2)}\n`, 'utf8');
  writeFileSync(markdownPath, `${markdown}\n`, 'utf8');
  writeFileSync(htmlPath, renderHtmlViewer(dossier), 'utf8');

  return { jsonPath, markdownPath, htmlPath };
}
